# Generated by Django 3.2.9 on 2021-11-05 21:35

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [UnaccentExtension(), TrigramExtension()]
