# Generated by Django 3.2.9 on 2021-11-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productorder_rentability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='rentability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
