# Generated by Django 3.2.9 on 2021-11-07 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211107_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='unitary_price_sell',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
    ]
