# Generated by Django 3.2.9 on 2021-11-07 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productorder_unitary_price_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitary_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='rentability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
    ]
