# Generated by Django 3.2.9 on 2021-11-10 03:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211107_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-date', 'product', 'id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date', 'seller', 'client', 'id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='unitary_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='rentability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='unitary_price_sell',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
